### ISSUE TITLE
CONFIG_WIFI_SSID

### ISSUE THREAD

**Issue by jeancode** [Xinyuan-LilyGO/T-Watch-2021#2]
![erreo eso](https://user-images.githubusercontent.com/19756878/140024508-64bff315-a468-4c9f-b5b0-2dc9a3c96929.PNG)

**Comment by cosismo** [comment]
You need to configure your WiFi credentials adding the following lines in include/config.h

#define CONFIG_WIFI_SSID "myWiFiNetwork"
#define CONFIG_WIFI_PASS "pleaseHackMe"
