### ISSUE TITLE
error on ACC sample for arduino 1.8.5 when using the copied library

### ISSUE THREAD

**Issue by F99** [Xinyuan-LilyGO/T-Watch-2021#3]
C:\Users\F70\Documents\Arduino\libraries\TWatch_2021_Library\src\drive\bma423.cpp: In member function 'void TWatchClass::AccSensor_Set_Feature_CB(uint8_t, irq_Fun_cb_t)':

C:\Users\F70\Documents\Arduino\libraries\TWatch_2021_Library\src\drive\bma423.cpp:284:9: error: '_bma_irq_cb' was not declared in this scope

**Comment by LilyGO** [comment]
I recompiled some ACC routines. It doesn't seem to find your error. Did you uncomment the corresponding model in TWatch_config.h?

**Comment by F99** [comment]
yes, it is the old version, I used 
#define TWatch2021_V1

**Comment by LilyGO** [comment]
Can you see what the version number on the board is?
TWatch2021_V1, I will reproduce it and update it in the next version

**Comment by F99** [comment]
It's the early version with INT1:IO22 and INT2:IO39 on BMA423 as shown on the instruction sheet. On the board I can see nothing.
Also I have flashed it successfully with the other repo https://github.com/sharandac/My-TTGO-Watch which is running ok.

**Comment by LilyGO** [comment]
The difference between the two versions and the V1 version is that there is no RTC interrupt. Version V1.2 consolidates all interrupts on one pin.

**Comment by F99** [comment]
The sheet only names SDA:IO26 and SCL:IO25 and no interrupt for RTC at this version. But that doesn't explain the errors at build stage.

**Comment by LilyGO** [comment]
I've re-updated the new library files to fix some of the bugs caused by the outage. Please try compiling with this library again.

**Comment by LilyGO** [comment]
The problem has not been updated for a long time, hang first
