### ISSUE TITLE
Reboot loop

### ISSUE THREAD

**Issue by MenneBos** [Xinyuan-LilyGO/T-Watch-2021#5]
Hello, I just received the T Watch 2021 and uploaded the latest version from Github in VSC and created a project in PlatformIO.
After the installation I performed on upload to the T-watch.

I used the standaard platform.ini file. 

I use the --environment pico32_LIGHT_EDITION .
After a succesfull build and flash of the code, it mentions on the serial port: 

**_rst:0x1 (POWERON_RESET),boot:0x3 (DOWNLOAD_BOOT(UART0/UART1/SDIO_REI_REO_V2))
waiting for download_**

and after pushing the boot button the loop begins:

_**Rebooting...
ets Jul 29 2019 12:21:46

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 271414342, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:1044
load:0x40078000,len:10124
load:0x40080400,len:5828
entry 0x400806a8
E (73) psram: Not a valid or known package id: 6
abort() was called at PC 0x40087feb on core 0

ELF file SHA256: 0000000000000000

Backtrace: 0x4008e734:0x3ffc93f0 0x4008e9ad:0x3ffc9410 0x40087feb:0x3ffc9430 0x4012c81a:0x3ffc9460 0x400ea2b0:0x3ffc9480 0x400ea1e5:0x3ffc94a0 0x400eb631:0x3ffc94c0 0x4012c99b:0x3ffc94f0 0x4008f9b2:0x3ffc9510**_

Any idea what can cause this issue?

**Comment by LilyGO** [comment]
Do you mean a reset because the PSRAM cannot be turned on.
The psram opening method of ESP32-PICO needs to add the following parameters
build_flags =
-DBOARD_HAS_PSRAM
-mfix-esp32-psram-cache-issue
-mfix-esp32-psram-cache-strategy=memw

**Comment by MenneBos** [comment]
Thanks for the feedback. I have these lines you mentioned in the platform.ini file.
[env:pico32_LIGHT_EDITION]
build_flags =
	-D DEBUG=1
	-D ARDUINO_ESP32_PICO
	-D LUA_C89_NUMBERS
	# -D BLUETOOTH_COMPANION
	-D BOARD_HAS_PSRAM
	-mfix-esp32-psram-cache-issue
	-mfix-esp32-psram-cache-strategy=memw

Some other findings:
- I do not have to push any button Boot / Reset to enter in the boot mode.
- I do not see anything on the screen

Not sure what the issue is?
- PSRAM
- Broken watch -- I don't know if it is broken as the the watch enters in a reboot loop. Downloading the code is working fine, The reset button is working -- I tested this during the reboot loop and it resets based on the Reset button.

**Comment by LilyGO** [comment]
Will he reset if he uploads a normal bilnk program? If not, there may be a bug in my SDK. I need your help to reproduce this problem. @MenneBos

**Comment by MenneBos** [comment]
Good idea, I will try your suggestion tomorrow and will post the result

**Comment by MenneBos** [comment]
Hi,

I uploaded the blink program successfully and made a reset using the Twatch button. The second reboot is caused by the push of the reset button.

See below the serial output:

**--- Terminal on COM7 | 115200 8-N-1
--- Available filters and text transformations: colorize, debug, default, direct, esp32_exception_decoder, hexlify, log2file, nocontrol, printable, 
send_on_enter, time
--- More details at https://bit.ly/pio-monitor-filters
--- Quit: Ctrl+C | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H
ets Jul 29 2019 12:21:46

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 271414342, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:1044 
load:0x40078000,len:10124
load:0x40080400,len:5828
entry 0x400806a8
Turning off the LED
Turning on the LED
Turning off the LED
Turning on the LED
Turning off the LED
Turning on the LED
Turning off the LED
Turning on the LED
Turning off the LED
Turning on the LED
ets Jul 29 2019 12:21:46

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 271414342, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:1044
load:0x40078000,len:10124
load:0x40080400,len:5828
entry 0x400806a8
Turning off the LED
Turning on the LED
Turning off the LED
Turning on the LED
Turning off the LED
Turning on the LED**

There was not led on the TWatch that actually blinked.
Still strange that I do not need to put the watch in boot modus by pushing the Boot/reset button. It uploads always,

Any idea or a next step you want me to take?

Regards Menne

**Comment by LilyGO** [comment]
From the current situation, there is no reset phenomenon. There is a high probability that it is caused by a problem with the SDK. If possible, upload the code where the reset occurred for analysis.
